Save\SiteBundle\Entity\Tag:
    type: entity
    table: null
    repositoryClass: Save\SiteBundle\Repository\TagRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '60'
            unique: true
    lifecycleCallbacks: {  }
